# Generated by Django 6.0 on 2025-12-18 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget_transfert', models.BigIntegerField(default=0, help_text='En euros')),
                ('masse_salariale_actuelle', models.BigIntegerField(default=0, help_text='Salaire annuel total')),
                ('plafond_salarial_dncg', models.BigIntegerField(default=0, help_text='Limite imposée par la DNCG')),
                ('reputation', models.IntegerField(default=50, help_text="Score 0-100 influençant l'attractivité")),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('played', models.BooleanField(default=False)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('match_log', models.JSONField(blank=True, default=list)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='om_engine.club')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='om_engine.club')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Gardien'), ('DEF', 'Défenseur'), ('MID', 'Milieu'), ('FWD', 'Attaquant')], max_length=3)),
                ('overall_rating', models.IntegerField(help_text='Niveau global 0-100')),
                ('form_factor', models.FloatField(default=1.0, help_text='Multiplicateur de forme (ex: 1.1 = en feu)')),
                ('injury_prone', models.FloatField(default=0.1, help_text='Probabilité de blessure')),
                ('market_value', models.BigIntegerField(help_text='Valeur estimée transfert')),
                ('wage', models.BigIntegerField(help_text='Salaire annuel')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='om_engine.club')),
            ],
        ),
    ]
