-- Effectif OM : champs affichage (numero, age, poste detaille, stats saison, coach)

ALTER TABLE clubs ADD COLUMN IF NOT EXISTS coach TEXT;

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS jersey_number INTEGER,
  ADD COLUMN IF NOT EXISTS age INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS position_label TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS matches_played INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS goals INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS assists INTEGER NOT NULL DEFAULT 0;

ALTER TABLE players ALTER COLUMN market_value DROP NOT NULL;
